project:
  type: book
  output-dir: _site

book:
  title: "Data Concepts and Applications"
  subtitle: Course Handbook
  author:
    - name: 
        given: Ernest
        family: Guevarra        
        literal: Ernest Guevarra
      degrees:
        - MD
        - MPH
      attributes:
        corresponding: true
      orcid: 0000-0002-4887-4415
      url: https://ernest.guevarra.io
      email: ernest@guevarra.io
      affiliations: 
        - name: University of Oxford
          department: Nuffield Department of Medicine
          group: Centre for Tropical Medicine and Global Health
          address: Peter Medawar Building for Pathogen Research, South Parks Road
          city: Oxford
          country: United Kingdom
          postal-code: OX1 3SY
          url: https://www.tropoicalmedicine.ox.ac.uk/study-with-us/msc-ihtm
    - name: 
        given: Proochista
        family: Ariana
        literal: Proochista Ariana
      degrees:
        - MS
        - DPhil
        - PGDipLATHE
      orcid: 0000-0002-0154-2237
      url: https://proochsita.com
      email: proochista.ariana@ndm.ox.ac.uk
      affiliations: 
        - name: University of Oxford
          department: Nuffield Department of Medicine
          group: Centre for Tropical Medicine and Global Health
          address: Peter Medawar Building for Pathogen Research, South Parks Road
          city: Oxford
          country: United Kingdom
          postal-code: OX1 3SY
          url: https://www.tropoicalmedicine.ox.ac.uk/study-with-us/msc-ihtm
  date: last-modified
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - part: Data Governance
      chapters:
        - 01-introduction.qmd
        - 02-all-about-data.qmd
    - part: Case Studies
      chapters:
        - 03-case-study-one.qmd
        - 04-case-study-two.qmd
        - 05-case-study-three.qmd
        - 06-case-study-four.qmd
        - 07-case-study-five.qmd
    - references.qmd
  # appendices: 
  #   - 12-mobile-device-setup.qmd
  #   - 13-odk-setup.qmd
  cover-image: images/top_logo.jpg
  search: true
  repo-url: https://github.com/tamanh-oxford/top-data-concepts-applications/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [linkedin, twitter, facebook]
  google-analytics: 
    tracking-id: ""
    anonymize-ip: true

crossref:
  appendix-title: Appendix
  appendix-delim: ":"

bibliography: references.bib
csl: apa-single-spaced.csl

format:
  html:
    theme: zephyr
    highlight-style: breeze-light
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 3
    highlight-style: breeze-light
    include-in-header: 
      text: |
        \usepackage{imakeidx}
        \makeindex[intoc=true, columns=2, columnseprule=true]
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/top_logo.jpg
    toc: true
    toc-depth: 3
    highlight-style: breeze-light